import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { Navigation } from "./components/navigation";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-foreground  text-background h-16 flex items-center justify-center">
         {/*<h1 className="text-lg font-bold">Welcome to Our Application</h1>*/}
        <Navigation />
        </header>

        <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start">
          {children}
        </main>
        
        <footer className="bg-foreground text-background h-16 flex items-center justify-center">
          <p className="text-sm">
            &copy; {new Date().getFullYear()} All rights reserved. Lewiii_Thee
            _G
          </p>
        </footer>
      </body>
    </html>
  );
}
